### ISSUE TITLE
Module not found: Can't resolve 'graphql'

### ISSUE THREAD

**Issue by cnscorpions** [nestjs-shopify/example-nx-app#2]
Thank you for your good work 😄.

I keep tightly on the guide.

But after `npx nx run web:serve`, it throws an error as follows:
```
error - ../../node_modules/graphql-tag/lib/index.js:2:0
Module not found: Can't resolve 'graphql'

Import trace for requested module:
../../node_modules/@apollo/client/core/index.js
../../node_modules/@apollo/client/index.js
./pages/_app.tsx

https://nextjs.org/docs/messages/module-not-found
```

Env:
OS win10 Pro
Node v16.14.2
Yarn 1.22.5

Please help, thank you in advance.

**Comment by tolgap** [comment]
Hi I just went through the README steps:

```console
git clone --depth 1 git@github.com:nestjs-shopify/example-nx-app.git
  Cloning into 'example-nx-app'...
  remote: Enumerating objects: 92, done.
  remote: Counting objects: 100% (92/92), done.
  remote: Compressing objects: 100% (76/76), done.
  remote: Total 92 (delta 6), reused 70 (delta 4), pack-reused 0
  Receiving objects: 100% (92/92), 353.62 KiB | 1.41 MiB/s, done.
  Resolving deltas: 100% (6/6), done.
```

```console
cd example-nx-app
npm install
  added 1547 packages, and audited 1557 packages in 33s
```

```console
cp .env.example .env
vi .env
```

Ran the migrations
```console
cd apps/api
npx mikro-orm schema:update -r
cd ../..
```

And then ran the apps:

In window 1:
```console
cd example-nx-app
npx nx run web:serve

> nx run web:serve:development

info  - Loaded env from apps/web/.env
[ info ]  found proxy configuration at /Users/tolga/Projects/Tolgap/example-nx-app/apps/web/proxy.conf.json
info  - automatically enabled Fast Refresh for 1 custom loader
event - compiled client and server successfully in 2.4s (1461 modules)
[HPM] Proxy created: /api  -> http://localhost:8080
[ ready ] on http://localhost:8081
wait  - compiling / (client and server)...
event - compiled client and server successfully in 275 ms (1473 modules)
```

In window 2:
```console
cd example-nx-app
npx nx run api:serve

> nx run api:serve

chunk (runtime: main) main.js (main) 26.8 KiB [entry] [rendered]
webpack compiled successfully (35bc5ad402ea98e4)
Debugger listening on ws://localhost:9229/dbd51f05-75bb-45a5-9d6f-16d074a1dfe6
Debugger listening on ws://localhost:9229/dbd51f05-75bb-45a5-9d6f-16d074a1dfe6
For help, see: https://nodejs.org/en/docs/inspector
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [NestFactory] Starting Nest application...
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [InstanceLoader] AppModule dependencies initialized +21ms
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [InstanceLoader] MikroOrmModule dependencies initialized +0ms
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +1ms
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +1ms
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +1ms
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [InstanceLoader] ProductsModule dependencies initialized +0ms
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [InstanceLoader] ShopifyWebhooksModule dependencies initialized +0ms
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [MikroORM] [info] MikroORM version: 5.3.0
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [MikroORM] [discovery] ORM entity discovery started, using ReflectMetadataProvider
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [MikroORM] [discovery] - processing entity ShopEntity
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [MikroORM] [discovery] - processing entity SessionEntity
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [MikroORM] [discovery] - entity discovery finished, found 2 entities, took 7 ms
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [MikroORM] [info] MikroORM successfully connected to database apps/api/api.sqlite3
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [InstanceLoader] MikroOrmCoreModule dependencies initialized +1ms
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [InstanceLoader] MikroOrmModule dependencies initialized +0ms
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [InstanceLoader] MikroOrmModule dependencies initialized +0ms
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [InstanceLoader] SessionModule dependencies initialized +0ms
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [InstanceLoader] WebhooksModule dependencies initialized +0ms
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [InstanceLoader] ShopsModule dependencies initialized +0ms
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [InstanceLoader] AfterAuthModule dependencies initialized +0ms
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [InstanceLoader] ShopifyCoreModule dependencies initialized +1ms
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [InstanceLoader] ShopifyAuthOfflineModule dependencies initialized +0ms
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [InstanceLoader] ShopifyAuthOnlineModule dependencies initialized +0ms
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [RoutesResolver] ShopifyAuthOfflineController {/api/offline}: +4ms
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [RouterExplorer] Mapped {/api/offline/auth, GET} route +1ms
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [RouterExplorer] Mapped {/api/offline/callback, GET} route +0ms
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [RoutesResolver] ShopifyAuthOnlineController {/api/online}: +1ms
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [RouterExplorer] Mapped {/api/online/auth, GET} route +0ms
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [RouterExplorer] Mapped {/api/online/callback, GET} route +0ms
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [RoutesResolver] ShopifyGraphqlController {/api/graphql}: +0ms
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [RouterExplorer] Mapped {/api/graphql, POST} route +0ms
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [RoutesResolver] ShopifyWebhooksController {/api/shopify/webhooks}: +1ms
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [RouterExplorer] Mapped {/api/shopify/webhooks, POST} route +0ms
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [RoutesResolver] ProductsController {/api/products}: +0ms
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [RouterExplorer] Mapped {/api/products/count, GET} route +0ms
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG [NestApplication] Nest application successfully started +3ms
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG 🚀 Application is running on: https://5230136263b1.ngrok.io/api
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG Login using: https://5230136263b1.ngrok.io/?shop=denham-com-d02.myshopify.com
[Nest] 29006  - 09/27/2022, 8:40:37 PM     LOG Install using: https://5230136263b1.ngrok.io/api/offline/auth?shop=denham-com-d02.myshopify.com
[Nest] 29006  - 09/27/2022, 8:40:39 PM     LOG [MikroORM] [query] select `s0`.* from `sessions` as `s0` where `s0`.`id` = '0c72e58b-b40a-4048-895d-91e8e949cb20' limit 1 [took 1 ms]
[Nest] 29006  - 09/27/2022, 8:40:39 PM     LOG [MikroORM] [query] begin
[Nest] 29006  - 09/27/2022, 8:40:39 PM     LOG [MikroORM] [query] insert into `sessions` (`id`, `is_online`, `shop`, `state`) values ('0c72e58b-b40a-4048-895d-91e8e949cb20', true, 'denham-com-d02.myshopify.com', '965646265579245') [took 0 ms]
[Nest] 29006  - 09/27/2022, 8:40:39 PM     LOG [MikroORM] [query] commit
```

At no point did I receive any errors about `graphql` package.

Are you certain that you're running the application in the root folder? You should run the apps from their own folder. You should *_not_ * be in `apps/web` or `apps/api`. You should simply be at the root folder: `example-nx-app`.

**Comment by cnscorpions** [comment]
failed again.

```
npm ERR! code 1
npm ERR! path F:\coding\shopify-dev\example-nx-app\node_modules\@mikro-orm\sqlite\node_modules\sqlite3
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build        
npm ERR! Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js 
configure --fallback-to-build --module=F:\coding\shopify-dev\example-nx-app\node_modules\@mikro-orm\sqlite\node_modules\sqlite3\lib\binding\napi-v6-win32-unknown-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=F:\coding\shopify-dev\example-nx-app\node_modules\@mikro-orm\sqlite\node_modules\sqlite3\lib\binding\napi-v6-win32-unknown-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.9
npm ERR! node-pre-gyp info using node@16.14.2 | win32 | x64
npm ERR! node-pre-gyp info check checked for "F:\coding\shopify-dev\example-nx-app\node_modules\@mikro-orm\sqlite\node_modules\sqlite3\lib\binding\napi-v6-win32-unknown-x64\node_sqlite3.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/TryGhost/node-sqlite3/releases/download/v5.0.10/napi-v6-win32-unknown-x64.tar.gz
npm ERR! node-pre-gyp ERR! install request to https://github.com/TryGhost/node-sqlite3/releases/download/v5.0.10/napi-v6-win32-unknown-x64.tar.gz failed, reason: read ECONNRESET
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for sqlite3@5.0.10 and node@16.14.2 (node-v93 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error request to https://github.com/TryGhost/node-sqlite3/releases/download/v5.0.10/napi-v6-win32-unknown-x64.tar.gz failed, reason: read ECONNRESET
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.14.2 | win32 | x64
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.14.2 | win32 | x64
npm ERR! gyp info find Python using Python version 3.6.0 found at "C:\Users\gavin\AppData\Local\Programs\Python\Python36\python.exe"        
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:363:14)
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:384:16
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:406:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
npm ERR! gyp ERR! System Windows_NT 10.0.19044
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=F:\\coding\\shopify-dev\\example-nx-app\\node_modules\\@mikro-orm\\sqlite\\node_modules\\sqlite3\\lib\\binding\\napi-v6-win32-unknown-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=F:\\coding\\shopify-dev\\example-nx-app\\node_modules\\@mikro-orm\\sqlite\\node_modules\\sqlite3\\lib\\binding\\napi-v6-win32-unknown-x64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=6" "--node_napi_label=napi-v6"
npm ERR! gyp ERR! cwd F:\coding\shopify-dev\example-nx-app\node_modules\@mikro-orm\sqlite\node_modules\sqlite3
npm ERR! gyp ERR! node -v v16.14.2
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=F:\coding\shopify-dev\example-nx-app\node_modules\@mikro-orm\sqlite\node_modules\sqlite3\lib\binding\napi-v6-win32-unknown-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=F:\coding\shopify-dev\example-nx-app\node_modules\@mikro-orm\sqlite\node_modules\sqlite3\lib\binding\napi-v6-win32-unknown-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (F:\coding\shopify-dev\example-nx-app\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.19044
npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "F:\\coding\\shopify-dev\\example-nx-app\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd F:\coding\shopify-dev\example-nx-app\node_modules\@mikro-orm\sqlite\node_modules\sqlite3
npm ERR! node-pre-gyp ERR! node -v v16.14.2
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.9
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gavin\AppData\Local\npm-cache\_logs\2022-09-28T02_07_28_896Z-debug-0.log
```

It seems that node-pre-gyp can not install sqlite3 at my local machine successfully. 

mikro-orm use sqlite3 under the hood?

backend code runs very well, and I may implement frontend myself 😂.

Thanks you, and close the issue.
